blank_issues_enabled: false
contact_links:
  - name: Discussions
    url: https://github.com/CogitatorTech/santa-2025-solution-editor/discussions
    about: Please ask and answer general questions here
